// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhljfpOk_s2uZhNVT04XZUyNflsjNApl0',
    appId: '1:857584310644:web:650e8d3ce7c1c9e726b421',
    messagingSenderId: '857584310644',
    projectId: 'agrich-111be',
    authDomain: 'agrich-111be.firebaseapp.com',
    storageBucket: 'agrich-111be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT8eOsZAz34JuqFHRNAFkpzC_-oMRw9TY',
    appId: '1:857584310644:android:d1f286b79f4b113726b421',
    messagingSenderId: '857584310644',
    projectId: 'agrich-111be',
    storageBucket: 'agrich-111be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK68Ab1xBLL3eCIwuITbDGYbFEAQC7Q1M',
    appId: '1:857584310644:ios:8234756c1857382b26b421',
    messagingSenderId: '857584310644',
    projectId: 'agrich-111be',
    storageBucket: 'agrich-111be.appspot.com',
    iosBundleId: 'com.example.agrichapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK68Ab1xBLL3eCIwuITbDGYbFEAQC7Q1M',
    appId: '1:857584310644:ios:ba10125124795f7026b421',
    messagingSenderId: '857584310644',
    projectId: 'agrich-111be',
    storageBucket: 'agrich-111be.appspot.com',
    iosBundleId: 'com.example.agrichapp.RunnerTests',
  );
}
